### ISSUE TITLE
BungeeTablistPlus doesnt work

### ISSUE THREAD

**Issue by xcheez1** [Phoenix616/Snap#25] opened 2021-12-18 18:10 UTC
[20:05:59 ERROR] [BungeeTabListPlus]: An internal error occurred! Please send the following StackTrace to the developer in order to help resolving the problem
java.lang.NoClassDefFoundError: net/md_5/bungee/UserConnection
        at codecrafter47.bungeetablistplus.util.ReflectionUtil.getChannelWrapper(ReflectionUtil.java:37) ~[?:?]
        at codecrafter47.bungeetablistplus.managers.TabViewManager.createTabView(TabViewManager.java:126) ~[?:?]
        at codecrafter47.bungeetablistplus.managers.TabViewManager.onPlayerJoin(TabViewManager.java:71) ~[?:?]
        at codecrafter47.bungeetablistplus.listener.TabListListener.onPlayerJoin(TabListListener.java:45) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[?:?]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:47) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:453) ~[?:?]
        at de.themoep.snap.forwarding.listener.PostLoginListener.on(PostLoginListener.java:33) ~[?:?]
        at de.themoep.snap.forwarding.listener.Lmbda$550.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[Velocity.jar:3.1.1]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[Velocity.jar:3.1.1]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[Velocity.jar:3.1.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.UserConnection
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:85) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:67) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 19 more

**Comment by Phoenix616** [comment] 2021-12-18 19:50
Duplicate of #14

**Closed by Phoenix616** 2021-12-18 19:50 UTC
