### ISSUE TITLE
BungeeTabList error

### ISSUE THREAD

**Issue by SanderWxD** [Phoenix616/Snap#42] opened 2023-11-28 19:48 UTC
#### Used Version
Snap version: 1.1-SNAPSHOT (build 34)
Velocity version: 3.2.0-SNAPSHOT
  
#### Config
[snap.txt](https://github.com/Phoenix616/Snap/files/13492492/snap.txt)

#### Full Log
[latest.log](https://github.com/Phoenix616/Snap/files/13492478/latest.log)
 
#### Environment description
Proxy is running on Linux. Wouldn't be able to tell you what version.
 
#### What other programs/plugins are you running?
No other plugins on Snap. Outside of snap, the Proxy is only running ViaVersion, LuckPerms, NuVotifier and LiteBans

#### What is happening?
Plugin doesn't load properly. I've toggled both options in the config but no change. Is this something that can be fixed/I can fix?
Console keeps spamming: [Snap]: Error dispatching event ServerConnectedEvent(player=de.themoep.snap.forwarding.SnapPlayer@287471fa, server=de.themoep.snap.forwarding.SnapServer@5efc11d7) to listener codecrafter47.bungeetablistplus.managers.TabViewManager@6f667548
java.lang.AssertionError: Received ServerSwitchEvent for non-existent player SanderW (<- my IGN)

**Comment by Phoenix616** [comment] 2023-11-28 20:02
Duplicate of the pinned issue #14. BungeeTabListPlus will not work as it uses internal classes and not the pcugin API.

**Closed** 2023-11-28 20:02 UTC
