### ISSUE TITLE
CONNECTION CANCELLED

### ISSUE THREAD

**Issue by TymekSL** [Phoenix616/Snap#49] opened 2024-10-23 23:04 UTC
### What is happening?

When wantconnect server got message connection cancelled

### What did you expect to happen?

I want connect to server

### Version

Snap 1.2-pre 1 (build 35) Latest

### Config

```YAML
# Whether to register all forwarding listeners even though no plugin needs it
# This is required if a plugin tries to dynamically register events after its onEnable method was called
register-all-listeners=true
# The stats/metrics ID of this proxy, ideally the same as in the velocity.toml
stats-id=adce4f79-5c09-4b7b-92e9-2424a3bdb113
# Whether to throw exceptions when accessing methods that aren't supported
# Setting this to false makes them return sensible values but they might not be correct
throw-unsupported-exception=false
```

### Server/system Version

velocity-3.3.0-SNAPSHOT-436.jar

### Log

```shell
[01:00:47 WARN] [Snap]: Error dispatching event ServerConnectEvent(player=de.themoep.snap.forwarding.SnapPlayer@6b59823, target=null, reason=UNKNOWN, request=null, cancelled=true) to listener me.sloth_design.listeners.onServerConnectEvent@352067f5
java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.api.config.ServerInfo.getName()" because the return value of "net.md_5.bungee.api.event.ServerConnectEvent.getTarget()" is null
        at me.sloth_design.listeners.onServerConnectEvent.serverConnectEvent(onServerConnectEvent.java:34) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[?:?]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:467) ~[?:?]
        at de.themoep.snap.forwarding.listener.ServerConnectListener.on(ServerConnectListener.java:42) ~[?:?]
        at de.themoep.snap.forwarding.listener.Lmbda$134.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:676) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.event.VelocityEventManager$ContinuationTask.run(VelocityEventManager.java:602) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[01:01:10 INFO] [ajqueue]: Using LuckPerms for permissions.
[01:01:11 WARN] [Snap]: Error dispatching event ServerConnectEvent(player=de.themoep.snap.forwarding.SnapPlayer@6b59823, target=null, reason=UNKNOWN, request=null, cancelled=true) to listener me.sloth_design.listeners.onServerConnectEvent@352067f5
java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.api.config.ServerInfo.getName()" because the return value of "net.md_5.bungee.api.event.ServerConnectEvent.getTarget()" is null
        at me.sloth_design.listeners.onServerConnectEvent.serverConnectEvent(onServerConnectEvent.java:34) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[?:?]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:467) ~[?:?]
        at de.themoep.snap.forwarding.listener.ServerConnectListener.on(ServerConnectListener.java:42) ~[?:?]
        at de.themoep.snap.forwarding.listener.Lmbda$134.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:676) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.event.VelocityEventManager$ContinuationTask.run(VelocityEventManager.java:602) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[01:01:13 WARN] [Snap]: Error dispatching event ServerConnectEvent(player=de.themoep.snap.forwarding.SnapPlayer@6b59823, target=null, reason=UNKNOWN, request=null, cancelled=true) to listener me.sloth_design.listeners.onServerConnectEvent@352067f5
java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.api.config.ServerInfo.getName()" because the return value of "net.md_5.bungee.api.event.ServerConnectEvent.getTarget()" is null
        at me.sloth_design.listeners.onServerConnectEvent.serverConnectEvent(onServerConnectEvent.java:34) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[?:?]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:467) ~[?:?]
        at de.themoep.snap.forwarding.listener.ServerConnectListener.on(ServerConnectListener.java:42) ~[?:?]
        at de.themoep.snap.forwarding.listener.Lmbda$134.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:676) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.event.VelocityEventManager$ContinuationTask.run(VelocityEventManager.java:602) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[01:01:20 WARN] [Snap]: Error dispatching event ServerConnectEvent(player=de.themoep.snap.forwarding.SnapPlayer@6b59823, target=null, reason=UNKNOWN, request=null, cancelled=true) to listener me.sloth_design.listeners.onServerConnectEvent@352067f5
java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.api.config.ServerInfo.getName()" because the return value of "net.md_5.bungee.api.event.ServerConnectEvent.getTarget()" is null
        at me.sloth_design.listeners.onServerConnectEvent.serverConnectEvent(onServerConnectEvent.java:34) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[?:?]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:467) ~[?:?]
        at de.themoep.snap.forwarding.listener.ServerConnectListener.on(ServerConnectListener.java:42) ~[?:?]
        at de.themoep.snap.forwarding.listener.Lmbda$134.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:676) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.event.VelocityEventManager$ContinuationTask.run(VelocityEventManager.java:602) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[01:01:27 WARN] [Snap]: Error dispatching event ServerConnectEvent(player=de.themoep.snap.forwarding.SnapPlayer@6b59823, target=null, reason=UNKNOWN, request=null, cancelled=true) to listener me.sloth_design.listeners.onServerConnectEvent@352067f5
java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.api.config.ServerInfo.getName()" because the return value of "net.md_5.bungee.api.event.ServerConnectEvent.getTarget()" is null
        at me.sloth_design.listeners.onServerConnectEvent.serverConnectEvent(onServerConnectEvent.java:34) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[?:?]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:467) ~[?:?]
        at de.themoep.snap.forwarding.listener.ServerConnectListener.on(ServerConnectListener.java:42) ~[?:?]
        at de.themoep.snap.forwarding.listener.Lmbda$134.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:676) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.event.VelocityEventManager$ContinuationTask.run(VelocityEventManager.java:602) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[01:01:34 WARN] [Snap]: Error dispatching event ServerConnectEvent(player=de.themoep.snap.forwarding.SnapPlayer@6b59823, target=null, reason=UNKNOWN, request=null, cancelled=true) to listener me.sloth_design.listeners.onServerConnectEvent@352067f5
java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.api.config.ServerInfo.getName()" because the return value of "net.md_5.bungee.api.event.ServerConnectEvent.getTarget()" is null
        at me.sloth_design.listeners.onServerConnectEvent.serverConnectEvent(onServerConnectEvent.java:34) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[?:?]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:467) ~[?:?]
        at de.themoep.snap.forwarding.listener.ServerConnectListener.on(ServerConnectListener.java:42) ~[?:?]
        at de.themoep.snap.forwarding.listener.Lmbda$134.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:676) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.event.VelocityEventManager$ContinuationTask.run(VelocityEventManager.java:602) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[01:01:41 WARN] [Snap]: Error dispatching event ServerConnectEvent(player=de.themoep.snap.forwarding.SnapPlayer@6b59823, target=null, reason=UNKNOWN, request=null, cancelled=true) to listener me.sloth_design.listeners.onServerConnectEvent@352067f5
java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.api.config.ServerInfo.getName()" because the return value of "net.md_5.bungee.api.event.ServerConnectEvent.getTarget()" is null
        at me.sloth_design.listeners.onServerConnectEvent.serverConnectEvent(onServerConnectEvent.java:34) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[?:?]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:467) ~[?:?]
        at de.themoep.snap.forwarding.listener.ServerConnectListener.on(ServerConnectListener.java:42) ~[?:?]
        at de.themoep.snap.forwarding.listener.Lmbda$134.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:676) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.event.VelocityEventManager$ContinuationTask.run(VelocityEventManager.java:602) ~[velocity-3.3.0-SNAPSHOT-436.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

### What other programs/plugins are you running?

https://prnt.sc/rIpqau6vaxjV
https://prnt.sc/VpT54P15fQpV

**Comment by Phoenix616** [comment] 2024-10-23 23:13
Duplicate of #45

**Closed** 2024-10-23 23:13 UTC
